### PR TITLE
Scale with GameSettings.UI_Scale

### PR DESCRIPTION
**Pull request by KerballOne**
UI components rescaled and will scale with Game's UI scaler.  Upscaled icon files so they also scale

### CODE REVIEW

**Comment by kweeky** [comment]
@KerballOne do you have a public fork of the mod anywhere given updates seem to have ceased by TriggerAU and this PR never got merged?

I really miss this mod and it's completely unusable at 4K sadly.

**Comment by KerballOne** [comment]
> @KerballOne do you have a public fork of the mod anywhere given updates seem to have ceased by TriggerAU and this PR never got merged?
> 
> I really miss this mod and it's completely unusable at 4K sadly.

https://github.com/KerballOne/AlternateResourcePanel

**Comment by kweeky** [comment]
I've put your compiled KSPAlternateResourcePanel.dll in, but it seems to be the same as the one before (still seeing the non-scaled version - also the version number doesn't match - showing v2.11.0.0 instead of v2.11.0.1)

image

image

**Comment by KerballOne** [comment]
> I've put your compiled KSPAlternateResourcePanel.dll in, but it seems to be the same as the one before (still seeing the non-scaled version - also the version number doesn't match - showing v2.11.0.0 instead of v2.11.0.1)

Sorry, I had reverted my upscaling last year.  So my repo only had a minor adjustment to tooltip position.
I didn't really like the look of what I did to rescale it, and since so many other apps are too small at 4k, I decided to abandon 4k KSP entirely... and just played at 1440p which looks reasonable even for apps that do not scale.

But I went ahead and re-applied the changes that this PR made so you can see if you like it.  It's not fully implemented as this was my first attempt with modding.  But if you like it, feel free to use it as is.  But I won't put any more effort into it.  Enjoy.

https://github.com/KerballOne/AlternateResourcePanel/releases/tag/v2.11.0.1

**Comment by kweeky** [comment]
This is perfect for me, thank you! Works a treat! Really appreciate you putting the time into making this available for me (and for anyone else in the future stumbling upon this thread who is experiencing the same issue!) Thank you!

**Pull request closed without merging**
