### PR TITLE
Functional extension to optionally display the resources of all vessels within a 2km radius

### PR DESCRIPTION
**Pull request by mhoram-kerbin**
This functionality is especially useful for people building distributed bases with [USI Kolonization Systems](http://forum.kerbalspaceprogram.com/threads/79588).

screenshot16

### CODE REVIEW

**Comment by TriggerAu** [comment]
Sounds very cool - will try and get it tested/integrated soon

**Comment by mhoram-kerbin** [comment]
@TriggerAu
May I ask if you plan to release a new version with this patch anytime soon?

**Comment by TriggerAu** [comment]
I do, I'm just struggling to get time between Squad and work now. Will do my best for this weekend

**Comment by mhoram-kerbin** [comment]
Thanks for the info. Don't worry, if it takes more time!

**Comment by TriggerAu** [comment]
Got the other two mods updated - this one is next

**Comment by mhoram-kerbin** [comment]
Thanks for adding it into the new release. The way how you display the state of the buttons now is much more clean than the way I tried to accomplish it.

**Comment by TriggerAu** [comment]
no probs, sorry it took so long this working for Squad thing takes a lot of time .

The state button thing came to me cause I noticed how crap my original ones looked and it logicallly fed into  this as well, so good stuff. Thanks again for the work you did here

**Comment by mhoram-kerbin** [comment]
Don't worry about how long it took. Working for Squad is one of the best excuses available ;-)
One feature that I originally wanted to implement, was to additionally display the amount of resources in the active vessel (using your current stage <-> all stages graphics distinction).
Since that part of the code was non-trivial for me to understang (nested and-or if queries) I did not dig into that deeper and also don't intend to do so.

**Pull request merged**
